# This is a basic workflow to help you get started with Actions

name: FantasyPlayer Testing Release

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches:
      - 'testing'
    tags-ignore: '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goats.dev/ffxiv/tools/launcher/addons/Hooks/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        
      - name: Build
        run: dotnet build -c Release

      - name: Copy release artifacts to root
        run: Copy-Item "FantasyPlayer.Dalamud\bin\Release\net472\FantasyPlayer.Dalamud\*" -Destination .

      - name: Release
        id: release-and-upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./FantasyPlayer.Dalamud.json
            ./latest.zip
          prerelease: true
          tag_name: Testing-${{ github.run_number }}
          release_name: Fantasy Player - Test Release \#${{ github.run_number }}
