# This is a basic workflow to help you get started with Actions

name: FantasyPlayer Testing Release

# Controls when the action will run. Triggers the workflow on a pull request
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore FantasyPlayer.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goaaats.github.io/ffxiv/tools/launcher/addons/Hooks/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\"
        
      - name: Build
        run: msbuild FantasyPlayer.sln /p:Configuration=Debug
        
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FantasyPlayer-PR-${{ github.run_number }}.zip
          path: FantasyPlayer.Dalamud\bin\Debug\
