# This is a basic workflow to help you get started with Actions

name: FantasyPlayer Testing Release

# Controls when the action will run. Triggers the workflow on a pull request
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
        
      - name: Build
        run: dotnet build -c Debug
        
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FantasyPlayer-PR-${{ github.run_number }}.zip
          path: FantasyPlayer.Dalamud\bin\Debug\
